name: E2E Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  test-e2e-platform-api:
    name: Platform Service with Platform Cluster API
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install opencontrolplane-gen
        run: |
          go install github.com/openmcp-project/opencontrolplane-gen@v1.0.2

      - name: E2E Platform API
        run: |
          task template:dev:e2e watch=platform

  test-e2e-onboarding-api:
    name: Platform Service with Onboarding Cluster API
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install opencontrolplane-gen
        run: |
          go install github.com/openmcp-project/opencontrolplane-gen@v1.0.2

      - name: E2E Onboarding API
        run: |
          task template:dev:e2e watch=onboarding
